### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dukinMars** [fusarolimichele/DiAna_cleaning#2]
This is the best R code for faers analysis，while I want to find a way to read the download zip package because of the terrible Internet condition😂

**Comment by fusarolimichele** [comment]
Thank You! We are now working on the implementation of a probabilistic deduplication, but we will soon share a zip with the files ready for the analysis. Keep tuned!

**Comment by fusarolimichele** [comment]
Hi @dukinMars . Still working on the probabilistic deduplication, but you can find the zip with the FAERS cleaned here, ready for the download: https://osf.io/zqu89/files/osfstorage

Please let us know if you find problems or have suggestions!
