### ISSUE TITLE
Signal lost when concomitants are removed

### ISSUE THREAD

**Issue by aseessingh** [fusarolimichele/DiAna_cleaning#6]
I have been trying to do a disproportionality analysis for ramipril in the US,UK and Canada. I had curated the data about the reactions from OpenVigil, and filtered on the basis of listing in the SMPC documents from the various regulatory agencies. I had subsequently determined overall concomitants administered for the indication "hypertension" from OpenVigil.
Now, when I am conducting Disproportionality with DiAna with the list of concomitants as pids_concomittants and country specific cases as pids_country, no signal is seen as no cases are left. What should be the workaround for this? The code I am using is given below
![image](https://github.com/fusarolimichele/DiAna/assets/30181851/a4f08cab-e232-41e0-b8c4-02747d0a9a6f)

**Comment by fusarolimichele** [comment]
Dear aseesingh, note that R requires to be particularly careful with spelling. Two main errors I see are "Angioedema" (it should not be capital) and the function for disproportionality analysis, which should be disproportionality_analysis. Let me know if it is sufficient to fix it

**Comment by aseessingh** [comment]
Dear Michele,
Nope, it didn't

**Comment by fusarolimichele** [comment]
Could you show me the results you obtain and the current script? So that I can help you better

**Comment by eavly** [comment]
'acyclovir' is a spelling error too according to INN nomenclature. The correct spelling is 'aciclovir.' Please verify all instances accordingly.

**Comment by aseessingh** [comment]
<img width="1448" alt="Screenshot 2024-06-12 at 4 24 53 PM" src="https://github.com/fusarolimichele/DiAna/assets/30181851/f33df6fc-4f1d-495a-8c64-072b2c2ac2b1">
<img width="1128" alt="Screenshot 2024-06-12 at 4 25 02 PM" src="https://github.com/fusarolimichele/DiAna/assets/30181851/01ddb664-ce2a-49d9-8e30-b817e902d151">

**Comment by aseessingh** [comment]
the code is the same as you shared @fusarolimichele , just dropped the list I copied from the OpenVigil data into it

**Comment by fusarolimichele** [comment]
If you see the result it does see the event but not the drug. Can you check in your environment what drug_selected is at the moment?

**Comment by aseessingh** [comment]
ramipril

**Comment by fusarolimichele** [comment]
FAERS_version <- "23Q4"

## Import data ----------------------------------------------------------------
import("DRUG")
import("REAC")
import("DEMO")

# select only US reports
US <- "United States of America"
pids_US <- Demo[reporter_country==US|occr_country==US]$primaryid
# remove reports with amlodipine or aliskiren
pids_concomitants <- unique(Drug[substance %in% c("amlodipine","aliskiren")]$primaryid)
pids_pop <- setdiff(pids_US,pids_concomitants)

# define drug and event of interest
drug_selected <-  "ramipril"
reac_selected <- list("angioedema","cough") #I would extend the query to other terms

temp <- disproportionality_analysis(drug_selected,reac_selected,restriction=pids_pop)

**This is my result:**
   substance      event                                 primaryid_substance                                     primaryid_event   D_E  D_nE
      <fctr>      <ord>                                              <list>                                              <list> <num> <num>
1:  ramipril      cough 5763927,5873927,5891033,6238837,6244057,6761780,... 4663633,4687898,4662555,4681178,4705165,4705745,...   526 18378
2:  ramipril angioedema 5763927,5873927,5891033,6238837,6244057,6761780,... 4708957,4709270,4709366,4709367,4709369,4711529,...   136 18768
       D   nD_E      E    nD_nE ROR_median ROR_lower ROR_upper p_value_fisher Bonferroni IC_median IC_lower IC_upper              label_ROR
   <num>  <num>  <num>    <num>      <num>     <num>     <num>          <num>     <lgcl>     <num>    <num>    <num>                 <char>
1: 18904 149090 149616 11849655       2.27      2.08      2.48   1.098887e-60       TRUE      1.15     1.01     1.26 2.27 (2.08-2.48) [526]
2: 18904  16471  16607 11982274       5.27      4.41      6.24   4.007920e-52       TRUE      2.35     2.07     2.56 5.27 (4.41-6.24) [136]
                 label_IC     ROR_color      IC_color
                   <char>         <ord>         <ord>
1: 1.15 (1.01-1.26) [526] strong signal strong signal
2: 2.35 (2.07-2.56) [136] strong signal strong signal

**I still believe drug_selected is NA in your environment, try to run again this script and adjust it according to your needs**

**Comment by aseessingh** [comment]
the pids_pop dataset is just a column of numeric elements

**Comment by aseessingh** [comment]
I'll try once again. and what should I do if the analysis is not considering all reactions mentioned : I mention 5 and it only does it for 4. 
<img width="753" alt="Screenshot 2024-06-12 at 7 10 53 PM" src="https://github.com/fusarolimichele/DiAna/assets/30181851/51337b18-96dc-4426-8194-5924bf8f3230">
<img width="540" alt="Screenshot 2024-06-12 at 7 10 58 PM" src="https://github.com/fusarolimichele/DiAna/assets/30181851/02676713-fb9e-4905-b3e5-02ebdc855240">

**Comment by eavly** [comment]
This is because 'throat infection' is not a PT in the  MedDRA. The closest MedDRA PT is 'ear, nose, and throat infection'. When formulating your research query, please refer to the PTs recorded in the FAERS database.

**Comment by aseessingh** [comment]
Thank you for your help, I did a few tweaks and it worked
